// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyToAllClients():Promise<main.ApplyResult>;

export function DeleteServer(arg1:string):Promise<main.AppState>;

export function DisableClient(arg1:string,arg2:boolean):Promise<main.AppState>;

export function EnableClient(arg1:string):Promise<main.AppState>;

export function GetAppState():Promise<main.AppState>;

export function PreviewAppConfig():Promise<main.ClientConfigPreview>;

export function PreviewClientConfig(arg1:string):Promise<main.ClientConfigPreview>;

export function SaveServer(arg1:main.ServerInput):Promise<main.AppState>;
