// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyToAllClients() {
  return window['go']['main']['App']['ApplyToAllClients']();
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DisableClient(arg1, arg2) {
  return window['go']['main']['App']['DisableClient'](arg1, arg2);
}

export function EnableClient(arg1) {
  return window['go']['main']['App']['EnableClient'](arg1);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function PreviewAppConfig() {
  return window['go']['main']['App']['PreviewAppConfig']();
}

export function PreviewClientConfig(arg1) {
  return window['go']['main']['App']['PreviewClientConfig'](arg1);
}

export function SaveServer(arg1) {
  return window['go']['main']['App']['SaveServer'](arg1);
}
